//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AchFile()
        {
            this.AchEntries = new HashSet<AchEntry>();
        }
    
        public int AchFileId { get; set; }
        public string SourcePath { get; set; }
        public int Core { get; set; }
        public int SystemYear { get; set; }
        public int AchFileStatusId { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ACTIVE_MACHINE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AchEntry> AchEntries { get; set; }
    }
}
