//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADJ
    {
        public long ADJ_ID { get; set; }
        public Nullable<int> CORE { get; set; }
        public Nullable<int> SYSTEM_YEAR { get; set; }
        public string sadjkey { get; set; }
        public string srecnum { get; set; }
        public string sadjtype { get; set; }
        public string spriortype { get; set; }
        public Nullable<double> radjamt { get; set; }
        public string sadjdate { get; set; }
        public string sstopdate { get; set; }
        public string sadjnum { get; set; }
        public string arrkeylen0 { get; set; }
        public string arrkeylen1 { get; set; }
        public string arrkeylen2 { get; set; }
        public string arrkeylen3 { get; set; }
        public string arrkeylen4 { get; set; }
        public string arrkeylen5 { get; set; }
        public string arrkeylen6 { get; set; }
        public string arrkeylen7 { get; set; }
        public string arrkeylen8 { get; set; }
        public string arrkeylen9 { get; set; }
        public Nullable<bool> ffms { get; set; }
        public Nullable<bool> fweeklycycle { get; set; }
        public Nullable<double> rowedconduit { get; set; }
        public string sadjtime { get; set; }
        public string sstoptime { get; set; }
        public string manualforATMcards { get; set; }
        public string semailkey { get; set; }
        public string sstate { get; set; }
        public string ccpaymentind { get; set; }
        public string sfeeadjind { get; set; }
        public string lastupdatedatetime { get; set; }
        public string sweeklycycledate { get; set; }
        public string sweeklycycletime { get; set; }
        public string sACHDebitInd { get; set; }
        public string sClosedLoanInd { get; set; }
        public string sIntuitAckID { get; set; }
        public string SIMMind { get; set; }
        public string sForcedAdjInd { get; set; }
        public string sTraceNumber { get; set; }
        public string sEffectiveDate { get; set; }
        public string sFileDate { get; set; }
        public string sTransmitterEFIN { get; set; }
        public string adjrecsent { get; set; }
        public string sCashMgmtInd { get; set; }
        public string sFeePayTransactID { get; set; }
        public Nullable<bool> fJHEarlyFunding { get; set; }
        public string sSettlementDate { get; set; }
        public string filler { get; set; }
        public string RecordHash { get; set; }
        public long LastUpdateTimeStamp { get; set; }
        public System.DateTime DBCreateDate { get; set; }
        public System.DateTime DBUpdateDate { get; set; }
    }
}
