//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM
    {
        public long COM_ID { get; set; }
        public Nullable<int> CORE { get; set; }
        public Nullable<int> SystemYear { get; set; }
        public string Source { get; set; }
        public string scomkey { get; set; }
        public string srecnum { get; set; }
        public string sseqnum { get; set; }
        public string sdept { get; set; }
        public string sTag { get; set; }
        public string sintuitid { get; set; }
        public string comment { get; set; }
        public string lastupdatedatetime { get; set; }
        public long LastUpdateTimeStamp { get; set; }
        public System.DateTime DBCreateDate { get; set; }
        public System.DateTime DBUpdateDate { get; set; }
    }
}
