//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long CommentId { get; set; }
        public Nullable<int> Core { get; set; }
        public Nullable<int> SystemYear { get; set; }
        public string Source { get; set; }
        public string CommentKey { get; set; }
        public int RecordNumber { get; set; }
        public int SequenceNumber { get; set; }
        public string Department { get; set; }
        public string Tag { get; set; }
        public string IntuitId { get; set; }
        public Nullable<int> CommentTypeId { get; set; }
        public string commentSource { get; set; }
        public string CommentText { get; set; }
        public string lastupdatedatetime { get; set; }
        public Nullable<long> LastUpdateTimeStamp { get; set; }
        public System.DateTime DBCreateDate { get; set; }
        public System.DateTime DBUpdateDate { get; set; }
    }
}
