//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTLinking
    {
        public int Id { get; set; }
        public Nullable<int> Transmitter_ID { get; set; }
        public Nullable<int> Master_ID { get; set; }
        public Nullable<int> CTERO_ID { get; set; }
        public string IntuitACKID { get; set; }
        public string OfficeID { get; set; }
        public string TranUse { get; set; }
        public System.DateTime RecordCreate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string Unused { get; set; }
        public string SystemYearImport { get; set; }
    
        public virtual CTMasterInfo CTMasterInfo { get; set; }
        public virtual CTTransmitter CTTransmitter { get; set; }
    }
}
