//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISB
    {
        public long DISB_ID { get; set; }
        public Nullable<int> CORE { get; set; }
        public Nullable<int> SYSTEM_YEAR { get; set; }
        public string sdisbkey { get; set; }
        public string srecnum { get; set; }
        public string sdisbtype { get; set; }
        public string spriortype { get; set; }
        public Nullable<double> rdisbamt { get; set; }
        public string swaitdate { get; set; }
        public string sdisbdate { get; set; }
        public string scleardate { get; set; }
        public string sstopdate { get; set; }
        public string schecknum { get; set; }
        public string sverified { get; set; }
        public string sdisbnum { get; set; }
        public string arrkeylen { get; set; }
        public string rtn { get; set; }
        public string dan { get; set; }
        public string accttype { get; set; }
        public string soldchecknum { get; set; }
        public Nullable<bool> fprepfeediscl { get; set; }
        public string spriordebtflag { get; set; }
        public string sdebtbankcode { get; set; }
        public Nullable<bool> fralrtfeediscl { get; set; }
        public Nullable<bool> fstatefeediscl { get; set; }
        public Nullable<bool> fCCdebtdiscl { get; set; }
        public Nullable<bool> firsfundeddiscl { get; set; }
        public Nullable<bool> fstatefundeddiscl { get; set; }
        public Nullable<bool> freprintflag { get; set; }
        public string sadjflag { get; set; }
        public string scashmachineflag { get; set; }
        public Nullable<bool> fweeklycycle { get; set; }
        public string termid { get; set; }
        public string cwauthnum { get; set; }
        public string recordcreatetime { get; set; }
        public string specialdisbflag { get; set; }
        public string swaittime { get; set; }
        public string sdisbtime { get; set; }
        public string sstoptime { get; set; }
        public string scleartime { get; set; }
        public string sreleasedate { get; set; }
        public string sweeklycycledate { get; set; }
        public string sweeklycycletime { get; set; }
        public string suserdisbtype { get; set; }
        public Nullable<long> wnumverified { get; set; }
        public string solddisbnum { get; set; }
        public string stationid { get; set; }
        public string atmresponse { get; set; }
        public string atmauditno { get; set; }
        public string sstate { get; set; }
        public string snamec { get; set; }
        public string retailflag { get; set; }
        public string achholdflag { get; set; }
        public string lastupdatedatetime { get; set; }
        public string sIntuitAckID { get; set; }
        public string sHoldFlag { get; set; }
        public string sRetToIRSInd { get; set; }
        public string sTraceNumber { get; set; }
        public string sRetCode { get; set; }
        public string sCommentPrint { get; set; }
        public string CardUpdateDateTime { get; set; }
        public string sTransmitterEFIN { get; set; }
        public string sRevRejInd { get; set; }
        public string disbrecsent { get; set; }
        public string sbatchid { get; set; }
        public string TPGFeeInd { get; set; }
        public string swcitemid { get; set; }
        public string sEROFeeAdvInd { get; set; }
        public Nullable<double> rFiller { get; set; }
        public string cardloadedind { get; set; }
        public string sIsJHCard { get; set; }
        public string sIsJHLoanDisb { get; set; }
        public string sCardTypeInd { get; set; }
        public string sLibertyFunder { get; set; }
        public string sLibertyServicer { get; set; }
        public Nullable<bool> fIsPetzSB { get; set; }
        public string sFundsSentBackToIRS { get; set; }
        public string sBCMCheck { get; set; }
        public string sRTCPachtypeind { get; set; }
        public string sChecklessInd { get; set; }
        public string sSubDisbkey { get; set; }
        public string sClaimCodeInd { get; set; }
        public string sCashWebOrig { get; set; }
        public string sRemoteChkInd { get; set; }
        public string sHoldEmailSent { get; set; }
        public string filler { get; set; }
        public Nullable<double> ravailable1 { get; set; }
        public string sReleaseHoldInd { get; set; }
        public string sEffectiveDate { get; set; }
        public Nullable<bool> fJHEarlyFunding { get; set; }
        public string sCardTranID { get; set; }
        public string RecordHash { get; set; }
        public long LastUpdateTimeStamp { get; set; }
        public System.DateTime DBCreateDate { get; set; }
        public System.DateTime DBUpdateDate { get; set; }
        public Nullable<bool> fCheckAuthorizationFeeDisclosure { get; set; }
        public Nullable<bool> fPointOfSaleDisclosure { get; set; }
        public Nullable<double> CheckFeeAmountToTran { get; set; }
        public Nullable<double> CheckFeeAmountToMaster { get; set; }
        public Nullable<double> CheckFeeAmountToSite { get; set; }
        public Nullable<double> CheckFeeAmountToProcessor { get; set; }
        public string SSettlementDate { get; set; }
        public Nullable<bool> fadvanceinterestdisc { get; set; }
        public Nullable<bool> DocProcessingFeeDisclosure { get; set; }
    }
}
