//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ERO()
        {
            this.EROLinkings = new HashSet<EROLinking>();
            this.FeeSplits = new HashSet<FeeSplit>();
        }
    
        public int Id { get; set; }
        public string EFIN { get; set; }
        public string LatestEnrollYear { get; set; }
        public string CompanyName { get; set; }
        public string EIN { get; set; }
        public string OwnersSSN { get; set; }
        public Nullable<System.DateTime> OwnersDOB { get; set; }
        public string AvailableforReconsideration { get; set; }
        public string ProcessInd { get; set; }
        public Nullable<bool> BeingReviewed { get; set; }
        public string StationID { get; set; }
        public Nullable<bool> SendToRiskInd { get; set; }
        public Nullable<bool> UserReviewedInd { get; set; }
        public string Appealed { get; set; }
        public Nullable<bool> fRiskHitFound { get; set; }
        public Nullable<bool> fRiskHitReviewed { get; set; }
        public string ForceOptIn { get; set; }
        public string NoCheckPrinting { get; set; }
        public string DoNotCall { get; set; }
        public string SARNASSummary { get; set; }
        public string SARNAPSummary { get; set; }
        public string SARCVI { get; set; }
        public string sFeeAdvanceReview { get; set; }
        public string CRMCompanyName { get; set; }
        public string CRMPhoneNumber { get; set; }
        public string ComplianceEmailAddress { get; set; }
        public string ComplianceESSInd { get; set; }
        public string SiteGroupCode { get; set; }
        public string ACHHoldFlag { get; set; }
        public string RejectRecordsInd { get; set; }
        public string NoAddressUpdateInd { get; set; }
        public System.DateTime RecordCreate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string IntuitCAN { get; set; }
        public string IntuitFirmName { get; set; }
        public string SFAccountID { get; set; }
        public Nullable<System.DateTime> SFLastIncluded { get; set; }
        public string Reserved { get; set; }
        public string PromoCode { get; set; }
        public string PNACompanyName { get; set; }
        public string PNAWebURL { get; set; }
        public Nullable<decimal> PNAPhone { get; set; }
        public Nullable<long> ShopId { get; set; }
        public Nullable<bool> RiskLockInd { get; set; }
        public Nullable<int> DisbursementPreferenceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EROLinking> EROLinkings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeSplit> FeeSplits { get; set; }
    }
}
