//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class EROAccountInfo
    {
        public int Id { get; set; }
        public Nullable<int> EROLinking_ID { get; set; }
        public string SystemYear { get; set; }
        public string BankName { get; set; }
        public string NameOnAccount { get; set; }
        public string RTN { get; set; }
        public string DAN { get; set; }
        public string AcctType { get; set; }
        public Nullable<bool> AllowAcctChanges { get; set; }
        public Nullable<decimal> DisbSum { get; set; }
        public Nullable<decimal> AdjSum { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<int> NumberFunded { get; set; }
        public Nullable<int> SPCVolume { get; set; }
        public Nullable<int> BPCVolume { get; set; }
        public Nullable<int> ACHVolume { get; set; }
        public Nullable<int> TPCardVolume { get; set; }
        public Nullable<int> InstantCardVolume { get; set; }
        public Nullable<int> StateVolume { get; set; }
        public Nullable<decimal> MiscAmountToCollect { get; set; }
        public Nullable<decimal> MiscAmountCollected { get; set; }
        public Nullable<double> MiscPercentToCollect { get; set; }
        public Nullable<decimal> SoftwareCollectAmountToCollect { get; set; }
        public Nullable<decimal> SoftwareCollectAmountCollected { get; set; }
        public Nullable<double> SoftwareCollectPercentToCollect { get; set; }
        public Nullable<decimal> FeeAdvanceAmountToCollect { get; set; }
        public Nullable<decimal> FeeAdvanceAmountCollected { get; set; }
        public Nullable<double> FeeAdvancePercentToCollect { get; set; }
        public System.DateTime RecordCreate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<decimal> TPGCreditDebtAmountToCollect { get; set; }
        public Nullable<decimal> TPGCreditDebtAmountCollected { get; set; }
        public Nullable<double> TPGCreditDebtPercentToCollect { get; set; }
        public Nullable<decimal> TransmitterDebtAmountToCollect { get; set; }
        public Nullable<decimal> TransmitterDebtAmountCollected { get; set; }
        public Nullable<double> TransmitterDebtPercentToCollect { get; set; }
        public Nullable<int> EroProductProviderID { get; set; }
        public Nullable<decimal> B2BInterestAmountToCollect { get; set; }
        public Nullable<decimal> B2BInterestAmountCollected { get; set; }
        public Nullable<double> B2BInterestPercentToCollect { get; set; }
        public Nullable<decimal> B2BPrincipalAmountToCollect { get; set; }
        public Nullable<decimal> B2BPrincipalAmountCollected { get; set; }
        public Nullable<double> B2BPrincipalPercentToCollect { get; set; }
        public Nullable<decimal> EROPYAdvanceDebtAmountToCollect { get; set; }
        public Nullable<decimal> EROPYAdvanceDebtAmountCollected { get; set; }
        public Nullable<double> EROPYAdvanceDebtPercentToCollect { get; set; }
        public Nullable<decimal> PreseasonAdvanceAmountToCollect { get; set; }
        public Nullable<decimal> PreseasonAdvanceAmountCollected { get; set; }
        public Nullable<double> PreseasonAdvanceAmountPercentToCollect { get; set; }
        public Nullable<decimal> SPAAmountToCollect { get; set; }
        public Nullable<decimal> SPAAmountCollected { get; set; }
        public Nullable<double> SPAAmountPercentToCollect { get; set; }
        public Nullable<decimal> TPPreSeasonDebtAmountToCollect { get; set; }
        public Nullable<decimal> TPPreSeasonDebtAmountCollected { get; set; }
        public Nullable<double> TPPreSeasonDebtPercentToCollect { get; set; }
        public bool BankChangeInd { get; set; }
        public Nullable<decimal> UnfundedTaxpayerCreditDebtAmountToCollect { get; set; }
        public Nullable<decimal> UnfundedTaxpayerCreditDebtAmountCollected { get; set; }
        public Nullable<double> UnfundedTaxpayerCreditDebtPercentToCollect { get; set; }
        public Nullable<decimal> PreseasonAdvanceCommitmentFeeAmountToCollect { get; set; }
        public Nullable<decimal> PreseasonAdvanceCommitmentFeeAmountCollected { get; set; }
        public Nullable<double> PreseasonAdvanceCommitmentFeePercentToCollect { get; set; }
        public Nullable<decimal> FeeAdvanceCommitmentFeeAmountToCollect { get; set; }
        public Nullable<decimal> FeeAdvanceCommitmentFeeAmountCollected { get; set; }
        public Nullable<double> FeeAdvanceCommitmentFeePercentToCollect { get; set; }
        public string EnrollmentEntityId { get; set; }
    
        public virtual EROLinking EROLinking { get; set; }
    }
}
