//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class EROLinking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EROLinking()
        {
            this.EROAccountInfoes = new HashSet<EROAccountInfo>();
            this.FeeAdvances = new HashSet<FeeAdvance>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Transmitter_ID { get; set; }
        public Nullable<int> Master_ID { get; set; }
        public Nullable<int> ERO_ID { get; set; }
        public string IntuitACKID { get; set; }
        public string JHOfficeID { get; set; }
        public string TranUse { get; set; }
        public System.DateTime RecordCreate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string Unused { get; set; }
        public string SFAccountID { get; set; }
        public Nullable<System.DateTime> SFLastIncluded { get; set; }
        public Nullable<System.DateTime> TransmitterImportDate { get; set; }
        public string SystemYearImport { get; set; }
        public string RemoteChkInd { get; set; }
        public Nullable<System.DateTime> TransmitterImportDate16 { get; set; }
        public string SystemYearImport16 { get; set; }
        public Nullable<System.DateTime> TransmitterImportDate17 { get; set; }
        public string SystemYearImport17 { get; set; }
        public Nullable<System.DateTime> TransmitterImportDate18 { get; set; }
        public string SystemYearImport18 { get; set; }
        public Nullable<System.DateTime> TransmitterImportDate19 { get; set; }
        public string SystemYearImport19 { get; set; }
        public Nullable<int> SubServiceBureauProviderId { get; set; }
        public Nullable<System.DateTime> TransmitterImportDate20 { get; set; }
        public string SystemYearImport20 { get; set; }
    
        public virtual ERO ERO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EROAccountInfo> EROAccountInfoes { get; set; }
        public virtual MasterInfo MasterInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeAdvance> FeeAdvances { get; set; }
    }
}
