//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeAdvance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeeAdvance()
        {
            this.FeeAdvanceDetails = new HashSet<FeeAdvanceDetail>();
        }
    
        public int Id { get; set; }
        public int EROLinking_ID { get; set; }
        public System.DateTime ProcessDate { get; set; }
        public System.DateTime AdvancingDate { get; set; }
        public decimal GrossFeeAmount { get; set; }
        public decimal NetFeeAmount { get; set; }
        public System.DateTime RecordCreate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string SystemYear { get; set; }
        public Nullable<int> AdvType { get; set; }
    
        public virtual EROLinking EROLinking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeAdvanceDetail> FeeAdvanceDetails { get; set; }
    }
}
