//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeSplit
    {
        public int FeeSplitId { get; set; }
        public int MasterId { get; set; }
        public Nullable<int> EroId { get; set; }
        public string SystemYear { get; set; }
        public int SplitType { get; set; }
        public decimal SplitAmount { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual ERO ERO { get; set; }
        public virtual MasterInfo MasterInfo { get; set; }
    }
}
