//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterInfo()
        {
            this.EROLinkings = new HashSet<EROLinking>();
            this.FeeSplits = new HashSet<FeeSplit>();
            this.MasterFeeAdvDetails = new HashSet<MasterFeeAdvDetail>();
        }
    
        public int Id { get; set; }
        public string MasterEFIN { get; set; }
        public string LastEnrollYear { get; set; }
        public string BusinessModel { get; set; }
        public string CompanyName { get; set; }
        public string EmailAddress { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string FaxPhone { get; set; }
        public string OfficePhone { get; set; }
        public string Website { get; set; }
        public System.DateTime RecordCreate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string SFAccountID { get; set; }
        public Nullable<System.DateTime> SFLastIncluded { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<int> Funded { get; set; }
        public string TSAInd { get; set; }
        public string NoShip { get; set; }
        public string FeeAdvOptIn { get; set; }
        public string FeeAdvSpecInd { get; set; }
        public Nullable<decimal> FeeAdvCap { get; set; }
        public Nullable<System.DateTime> FeeAdvOptInDate { get; set; }
        public Nullable<System.DateTime> FeeAdvOptOutDate { get; set; }
        public Nullable<long> ShopId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EROLinking> EROLinkings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeSplit> FeeSplits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterFeeAdvDetail> MasterFeeAdvDetails { get; set; }
    }
}
