//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterFeeAdvDetail
    {
        public int Id { get; set; }
        public Nullable<int> MasterId { get; set; }
        public string SystemYear { get; set; }
        public Nullable<decimal> CapAmount { get; set; }
        public string ParticipantStatus { get; set; }
        public Nullable<System.DateTime> CutOff { get; set; }
        public Nullable<System.DateTime> RecordCreate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string ParticipantStatusEarly30 { get; set; }
    
        public virtual MasterInfo MasterInfo { get; set; }
    }
}
