//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingFeeDetail
    {
        public long PendingFeeDetailId { get; set; }
        public long PendingFeeId { get; set; }
        public int PendingFeeTypeId { get; set; }
        public int FundingSourceId { get; set; }
        public Nullable<decimal> FeeAmountPending { get; set; }
        public Nullable<decimal> FeeAmountPaid { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
