//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISK
    {
        public long RISK_ID { get; set; }
        public Nullable<int> CORE { get; set; }
        public Nullable<int> SystemYear { get; set; }
        public string pssn { get; set; }
        public string status { get; set; }
        public string pmadd { get; set; }
        public string pmcity { get; set; }
        public string pmstate { get; set; }
        public string pmzipcode { get; set; }
        public string smadd { get; set; }
        public string smcity { get; set; }
        public string smstate { get; set; }
        public string smzipcode { get; set; }
        public string ppadd { get; set; }
        public string ppcity { get; set; }
        public string ppstate { get; set; }
        public string ppzipcode { get; set; }
        public string spadd { get; set; }
        public string spcity { get; set; }
        public string spstate { get; set; }
        public string spzipcode { get; set; }
        public string piddesc { get; set; }
        public string pidnum { get; set; }
        public string siddesc { get; set; }
        public string sidnum { get; set; }
        public string sssn { get; set; }
        public string efin { get; set; }
        public string fstat { get; set; }
        public string pfname { get; set; }
        public string plname { get; set; }
        public string sfname { get; set; }
        public string slname { get; set; }
        public string homephonenum { get; set; }
        public string workphonenum { get; set; }
        public string dateofbirth { get; set; }
        public string recordcreatedate { get; set; }
        public string recordcreatetime { get; set; }
        public string stationid { get; set; }
        public string arrerrors0 { get; set; }
        public string arrerrors1 { get; set; }
        public string arrerrors2 { get; set; }
        public string arrerrors3 { get; set; }
        public string arrerrors4 { get; set; }
        public string arrerrors5 { get; set; }
        public string arrerrors6 { get; set; }
        public string arrerrors7 { get; set; }
        public string arrerrors8 { get; set; }
        public string arrerrors9 { get; set; }
        public string lastupdatedatetime { get; set; }
        public string HRInd0 { get; set; }
        public string HRInd1 { get; set; }
        public string HRInd2 { get; set; }
        public string HRInd3 { get; set; }
        public string HRInd4 { get; set; }
        public string Lifestyle_DwellType { get; set; }
        public Nullable<int> Lifestyle_AssessedAmount { get; set; }
        public Nullable<bool> Lifestyle_ApplicantOwned { get; set; }
        public Nullable<bool> Lifestyle_FamilyOwned { get; set; }
        public Nullable<bool> Lifestyle_OccupantOwned { get; set; }
        public Nullable<bool> Lifestyle_NotPrimaryResidence { get; set; }
        public string Lifestyle_DateFirstSeen { get; set; }
        public string Lifestyle_DateFirstSeen2 { get; set; }
        public string Lifestyle_DateFirstSeen3 { get; set; }
        public Nullable<int> Lifestyle_NumberNonDerogs { get; set; }
        public string Lifestyle_DateLastUpdate { get; set; }
        public Nullable<bool> Lifestyle_RecentUpdate { get; set; }
        public string Lifestyle_LicenseType { get; set; }
        public Nullable<int> Demographic_Age { get; set; }
        public Nullable<bool> Demographic_SSNIssued { get; set; }
        public string Demographic_LowIssueDate { get; set; }
        public string Demographic_HighIssueDate { get; set; }
        public Nullable<bool> Demographic_NonUSssn { get; set; }
        public string Demographic_SSNIssueState { get; set; }
        public string Demographic_SSNFirstSeen { get; set; }
        public Nullable<bool> Financial_PhoneFullNameMatch { get; set; }
        public Nullable<bool> Financial_PhoneLastNameMatch { get; set; }
        public string Financial_NAPStatus { get; set; }
        public string Financial_CreditFirstSeen { get; set; }
        public Nullable<int> Property_PropertyOwnedTotal { get; set; }
        public Nullable<int> Property_PropertyOwnedAssessedTotal { get; set; }
        public Nullable<int> Property_PropertyHistoricallyOwned { get; set; }
        public string Property_DateMostRecentPurchase { get; set; }
        public string Property_DateFirstPurchase { get; set; }
        public Nullable<int> Derog_CriminalCount { get; set; }
        public Nullable<int> Derog_FilingCount { get; set; }
        public string Derog_DateLastSeen { get; set; }
        public string Derog_Disposition { get; set; }
        public Nullable<int> Derog_LiensHistoricalUnreleased { get; set; }
        public Nullable<int> Derog_LiensRecentUnreleasedCount { get; set; }
        public Nullable<int> Derog_JudgementsCount { get; set; }
        public Nullable<int> Derog_EvictionsCount { get; set; }
        public Nullable<int> Derog_ForeclosureCount { get; set; }
        public Nullable<int> Derog_TotalNumberDerogs { get; set; }
        public string Derog_DateLastDerog { get; set; }
        public string arrAddName0 { get; set; }
        public string arrAddName1 { get; set; }
        public string arrAddName2 { get; set; }
        public string arrAddName3 { get; set; }
        public string arrAddName4 { get; set; }
        public string arrAddName5 { get; set; }
        public string arrAddName6 { get; set; }
        public string arrAddName7 { get; set; }
        public string arrAddName8 { get; set; }
        public string arrAddName9 { get; set; }
        public string arrAddValue0 { get; set; }
        public string arrAddValue1 { get; set; }
        public string arrAddValue2 { get; set; }
        public string arrAddValue3 { get; set; }
        public string arrAddValue4 { get; set; }
        public string arrAddValue5 { get; set; }
        public string arrAddValue6 { get; set; }
        public string arrAddValue7 { get; set; }
        public string arrAddValue8 { get; set; }
        public string arrAddValue9 { get; set; }
        public string score { get; set; }
        public string verifssn { get; set; }
        public string pissueddate { get; set; }
        public string pissuedby { get; set; }
        public string pexpirationdate { get; set; }
        public string sissueddate { get; set; }
        public string sissuedby { get; set; }
        public string sexpirationdate { get; set; }
        public string modelscore { get; set; }
        public string pcitizen { get; set; }
        public string pcountry { get; set; }
        public string scitizen { get; set; }
        public string scountry { get; set; }
        public string holdppadd { get; set; }
        public string holdppcity { get; set; }
        public string holdppstate { get; set; }
        public string holdppzipcode { get; set; }
        public string PulledAppAddr { get; set; }
        public long LastUpdateTimeStamp { get; set; }
        public System.DateTime DBCreateDate { get; set; }
        public System.DateTime DBUpdateDate { get; set; }
    }
}
